### PR TITLE
Mark library as obsolete

### PR DESCRIPTION
**Pull request by ntl**
This depends on the Time and Time::Elapsed controls being first merged into the clock library (see https://github.com/eventide-project/clock/pull/1). The UUID controls, e.g. Controls::ID, are actually already under Identifier::UUID::Controls, albeit the names are slightly different. Here is a map of the old controls to the new ones:

| Previously                      | Currently                                    |
| ------------------------------- | -------------------------------------------- |
| Controls::ID.get                | Identifier::UUID::Controls::Incrementing.get |
| Controls::Time.reference        | Clock::Controls::Time.reference              |
| Controls::Time::Raw.example     | Clock::ControlS::Time::Raw.example           |
| Controls::Time::Elapsed.example | Clock::Controls::Time::Elapsed.example       |

### CODE REVIEW

**Comment by ntl** [comment]
We should restore the old `Time` and `Time::Elapsed` controls here, as they will have different interfaces in `Clock::Controls`.

**Comment by ntl** [comment]
The branch has been updated and the original `Controls::Time` namespace has been restored.

**Comment by sbellware** [comment]
Good stuff. Solid step forward.

🍏

**Comment by ntl** [comment]
@sbellware should I merge this PR? You merged the other one to clock, so I want to make sure I'm not breaking protocol...

**Comment by sbellware** [comment]
Oh! Yes. Sorry. Miscommunication.

**Pull request merged**
